# for Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: 1234
MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_DATABASE: mipueblo

# for Server Config
#CONTAINER_PORT: 8085
CONTAINER_PORT: 8080
ACTIVE_PROFILE: prod

# for Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: insert
EMAIL_PASSWORD: insert
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

# for UI Config
UI_APP_URL: http://localhost:4200

JWT_SECRET: asecret


##og works
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/mipueblo
#    password: 1234
#    username: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        globally_quoted_indentifiers: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#  sql:
#     init:
#       mode: always
#       continue-on-error: false